language: node_js
cache: yarn
node_js:
  - "8"

install:
  - yarn install

script:
  - NODE_ENV=production yarn parcel build --public-url '.' src/index.html  --experimental-scope-hoisting

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
    branch: master
