language: node_js
cache: yarn
node_js:
  - "8"

install:
  - yarn install

script:
  - yarn build --public-url 'https://quanbrew.github.io/neonao/'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
    branch: master
